

words = ["electricity", "donkey", "hardware", "xerox", "transistor", "computer", "desktop",
"engineering", "hangman", "circuit", "imagination", "robot", "memory", "power",
"submarine", "chess", "resistance", "matrix", "function", "laser", "mechanism",
"bodyguard", "titanic", "global", "ozone", "bridge", "technology", "spider", "universe",
"pyramid", "sphere", "member", "warning", "yourself", "screen", "language", "electric",
"system", "internet", "parameter", "traffic", "network", "filter", "nucleus", "rocket",
"automatic", "microphone", "cassette", "operation", "country", "beautiful", "missing",
"picture", "teacher", "superman", "undertaker", "alarm", "process", "keyboard", "monitor",
"electron", "certificate", "grandfather", "landmark", "relativity", "eraser", "assembly",
"design", "football", "human", "musician", "egyptian", "elephant", "queen", "receiver",
"message", "wallpaper", "nationality", "answer", "wrong", "statement", "forest", "nature",
"puzzle", "voltage", "current", "mathematics", "wisdom", "dream", "supermarket", "friend",
"database", "collection", "barrier", "project", "sunlight", "figure", "graph", "flower",
"battle", "hundred", "signal", "thousand", "transformation", "daughter", "flower", "result",
"communication", "microwave", "electronic", "peace", "wireless", "delete", "window", "child",
"brain", "control", "prophet", "freedom", "harbour", "confidence", "positive", "soldier",
"harvest", "hunger", "woman", "children", "stranger", "garden", "pleasure", "laughter",
"between", "recognition", "tomorrow", "autumn", "monkey", "spring", "winter", "monkey",
"classification", "typewriter", "success", "difference", "acoustics", "astronomy", "prayer",
"agreement", "sorrow", "christmas", "silver", "birthday", "championship", "friendship",
"comfortable", "diffusion", "murder", "policeman", "science", "desert", "basketball",
"blood", "funeral", "silence", "garment", "merchant", "spirit", "punishment", "sentence",
"measurement", "ocean", "digital", "illusion", "tyrant", "castle", "passion", "permission",
"magician", "remedy", "knowledge", "threshold", "number", "vision", "expectation",
"absence", "mystery", "morning", "device", "thoughts", "spirit", "future",
"mountain", "treasure", "machine", "whispering", "eternity", "reflection", "occupation",
"achievement", "lightning", "secret", "environment", "shepherd", "confusion", "element",
"grave", "promise", "honour", "reward", "temple", "distance", "eagle", "saturn", "jupiter",
"finger", "belief", "crystal", "fashion", "direction", "captain", "moment", "impossible",
"permission", "logic", "analysis", "password", "english", "equalizer", "simulation",
"emotion", "battle", "expression", "scissors", "trousers", "glasses", "department",
"dictionary", "chemistry", "induction", "detail", "widow", "wealth", "health", "education",
"disaster", "volcano", "poverty", "limitation", "perfect", "intelligence", "infinity",
"failure", "ignorance", "destination", "source", "resort", "satisfaction", "examination",
"frequency", "selection", "substitution", "kingdom", "pattern", "management", "existence",
"situation", "multiply", "treatment", "dollar", "intuition", "chapter", "magnet",
"desire", "command", "action", "consciousness", "enemy", "security", "object", "nature",
"happen", "happiness", "worry", "method", "tolerance", "error", "hesitation", "rescue",
"record", "tongue", "supply", "vibration", "stress", "despair", "restaurant", "material",
"television", "video", "audio", "layer", "mixture", "doorbell", "cousin", "beard", "priest",
"finance", "production", "invisible", "excitement", "afternoon", "office", "alphabet",
"illustration", "valley", "apartment", "necessary", "shortage", "almost", "furniture",
"blanket", "suggestion", "overflow", "demonstration", "challenge", "compact", "kernel",
"tower", "question", "problem", "pressure", "beast", "encouragement", "afraid", "quantity",
"cavity", "appearance", "wonderful", "matter", "dimension", "business", "doubt", "fortune",
"conversation", "reaction", "psychology", "superstition", "smash", "horseshoe", "liquid",
"surprise", "nothing", "ladder", "opposite", "reality", "genius", "string", "discovery",
"destruction", "expensive", "painting", "chicken", "wishing", "profession", "engineer",
"hatred", "possession", "criticism", "zebra", "harmony", "personality", "overcome",
"addition", "subtraction", "cipher", "encryption", "compression", "extension", "session",
"blessing", "meeting", "difficulty", "weapon", "against", "external", "internal", "prison",
"legend", "servant", "secondary", "license", "directory", "statistics", "generation",
"attraction", "sensitivity", "magnification", "someone", "symptom", "recipe", "metaphor",
"service", "family", "island", "planet", "butterfly", "diving", "strength", "mission",
"extreme", "opportunity", "illumination", "cable", "conflict", "interference", "witness",
"receiver", "transmitter", "channel", "company", "grocery", "devil", "angel", "admire",
"exactly", "document", "tutorial", "sound", "voice", "abbreviation", "abdomen", "ability",
"abrupt", "absolute", "absorption", "abstract", "academy", "acceleration", "acceptance",
"accident", "account", "acidification", "actress", "adaptation", "addiction", "adhesion",
"adjustment", "admiration", "adoption", "advanced", "adventure", "advertisement", "advice",
"agenda", "airport", "algorithm", "allocation", "aluminium", "ambiguity", "ambition",
"amphibian", "anaesthesia", "analogy", "anchor", "animation", "anode", "cathode", "antenna",
"apparent", "appendix", "approval", "approximation", "arbitrary", "architecture", "archive",
"arithmetic", "arrangement", "article", "ascending", "ashamed", "asleep", "assassination",
"assembly", "astonishment", "atmosphere", "awful", "bachelor", "backbone", "background",
"bacteria", "balance", "balloon", "banana", "barbecue", "baseball", "beaker", "beautiful",
"beggar", "behaviour", "benefit", "bidirectional", "biology", "blackboard", "blackmail",
"bladder", "bleeding", "blender", "bonus", "bottle", "bracket", "branch", "brilliant",
"bubble", "bucket", "budget", "bullet", "burglar", "butcher", "bypass", "cafeteria",
"calculator", "calibration", "campaign", "cancellation", "candidate", "candle", "capacity",
"carpenter", "carriage", "cartoon", "cascade", "casual", "catalyst", "category", "cathedral",
"cement", "ceremony", "chairman", "checkout", "chimney", "chocolate", "cigarette", "circuit",
"circumference", "civilization", "classroom", "clearance", "client", "coconut", "codification",
"coincidence", "colleague", "comfortable", "competition", "kangaroo", "kidnap", "kitchen",
"journal", "jockey", "iteration", "isometric", "isolation", "invitation", "interview",
"institution", "injection", "humanity", "housekeeper", "history", "heaven", "guidance",
"greenhouse", "glory", "foundation", "formula", "fluctuation", "fiction", "extraction",
"emission", "elasticity", "earthquake", "dynamic", "doctorate", "divorce", "derivative",
"nightmare", "virtue", "description"]
